---
- name: Create Basic Server on Hetzner Cloud
  hosts: localhost
  connection : local
  gather_facts: False
  vars:
    download_k8sworkshop: True
    myquery: "hcloud_server.{ip: ipv4_address, name: name}"
  tasks:
    - name: Bringing up Hetzner Servers
      include_tasks: hetzner-init.yml
      with_sequence: start="{{ node_start_id }}" end="{{ nodes }}"
    - debug:
        msg: "{{ groups }}"

    - meta: refresh_inventory
    - name: Pause
      pause:
        seconds: 10

- import_playbook: user-play.yml
- import_playbook: nodes-play.yml
- import_playbook: master-play.yml
- import_playbook: master-init.yml
- import_playbook: nodes-join.yml

- name: "-----------------------------------"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Information
    debug:
      msg: "You can now log in on the Master with ssh {{ e2m_user }}@{{ hostvars[groups['k8s_master_yes'][0]].ansible_host }}"
